image: golang:latest

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - make test

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  when: on_success
  only:
    - master
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/glyco1/respdb .
    - docker push $CI_REGISTRY/glyco1/respdb
