http-client:
  user-agent: "VarMed - varmed.qb.fcen.uba.ar"
  timeout: 120

http-server:
  port: 8888

varmed:
  job-workers: 4
  pipeline:
    structure-workers: 4

debug-print:
  enabled: true
  rulers:
    uniprot: true
    pdb: true

paths:
  data: "data/"
  uniprot: "data/uniprot/"
  pdb: "data/pdb/"
  jobs: "data/jobs/"
  fpocket: "data/fpocket/"
  clinvar: "data/clinvar/"
  pfam: "data/pfam/"
  foldx-bin: "bin/foldx/foldx"
  foldx-repair: "data/foldx/repair/"
  foldx-mutations: "data/foldx/mutations/"
  abswitch-bin: "bin/abswitch/abSwitch"
  abswitch: "data/abswitch/"
  tango-bin: "bin/tango/tango"
  tango: "data/tango/"
  file-ext: ".data"
