http-client:
  user-agent: "RespDB - respdb.qb.fcen.uba.ar"
  timeout: 120

http-server:
  port: 8888

respdb:
  job-workers: 1
  pipeline:
    structure-workers: 4
    enable-steps:
      binding: true
      exposure: true
      interaction: true
      secondary: true
      conservation: true
      stability: true

debug-print:
  enabled: true
  rulers:
    uniprot: true
    pdb: true

paths:
  data: "data/"
  uniprot: "data/uniprot/"
  pdb: "data/pdb/"
  jobs: "data/jobs/"
  fpocket: "data/fpocket/"
  clinvar: "data/clinvar/"
  pfam: "data/pfam/"
  foldx-bin: "bin/foldx/foldx"
  foldx-repair: "data/foldx/repair/"
  foldx-mutations: "data/foldx/mutations/"
  abswitch: "data/abswitch/"
  file-ext: ".data"
