http-client:
  user-agent: "VarQ - varq.qb.fcen.uba.ar"
  timeout: 120

http-server:
  port: 8888

database:
  type: "sqlite"
  host: ""
  port: 1234
  username: ""
  password: ""

varq:
  job-workers: 3
  pipeline:
    structure-workers: 16
    enable-steps:
      binding: true
      exposure: true
      interaction: true

debug-print:
  enabled: true
  rulers:
    uniprot: true
    pdb: true