http-client:
  user-agent: "RespDB - respdb.qb.fcen.uba.ar"
  timeout: 120

http-server:
  port: 8888

respdb:
  job-workers: 1
  pipeline:
    structure-workers: 4
    enable-steps:
      binding: true
      exposure: true
      interaction: true
      secondary: true
      conservation: true
      stability: true

debug-print:
  enabled: true
  rulers:
    uniprot: true
    pdb: true
