http-client:
  user-agent: "VarQ - varq.qb.fcen.uba.ar"
  timeout: 120

http-server:
  port: 8888
  
varq:
  job-workers: 1
  pipeline:
    structure-workers: 4
    enable-steps:
      binding: true
      exposure: true
      interaction: true

debug-print:
  enabled: true
  rulers:
    uniprot: true
    pdb: true