http-client:
  user-agent: "VarQ - varq.qb.fcen.uba.ar"
  timeout: 120

http-server:
  port: 3000

database:
  type: "sqlite"
  host: ""
  port: 1234
  username: ""
  password: ""

varq:
  fetch-workers: 16