name: Webpack
on: [push]

defaults:
  run:
    working-directory: web

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
